notes
elasticio/elasticio.github.io pull request #1240
Opened 2023-05-10 10:40 UTC by andrewreshitko

2023-05-10 10:49 UTC, HannaTrotsenko commented on content/_releases/23/19.md
> +* We added new `node_config` option `consume_raw_data`. This parameter configures the parsing behaviour in the webhook step. In case it is true, webhook step receives input message in raw structure.
to the Flow attributes

2023-05-10 13:48 UTC, HannaTrotsenko approved these changes

2023-05-10 13:48 UTC, HannaTrotsenko commented on content/_releases/23/19.md
> +{% include img.html max-width="100%" url="/assets/img/RN/2319/BigInt.png" title="BigInt" %}
@andrewreshitko here

2023-05-10 13:48 UTC, HannaTrotsenko approved these changes

2023-05-11 09:32 UTC, KMobbs requested changes

2023-05-11 09:32 UTC, KMobbs commented on content/_releases/23/19.md
> +* We added a new `node_config` option `consume_raw_data`. This parameter configures the parsing behaviour in the webhook step. In case it is true, the webhook step receives an input message in the ra
```suggestion
* We added a new `node_config` option `consume_raw_data` as a configuration option. This parameter configures the parsing behaviour in the webhook step. If selected, the webhook step receives an input message in the raw structure.
```

2023-05-11 10:40 UTC, HannaTrotsenko approved these changes

2023-05-11 10:40 UTC, HannaTrotsenko approved these changes

2023-05-11 10:58 UTC, KMobbs approved these changes

2023-05-11 11:10 UTC, merged