Fixes 27.05.2024
elasticio/elasticio.github.io pull request #1376
Opened 2024-05-29 08:59 UTC by Glico21

- Update parallel processing title in managing flows article
- Update API endpoints title in copy and export flow article

2024-05-29 09:01 UTC, andrewreshitko approved these changes

2024-05-29 09:01 UTC, MykytaDuniashev approved these changes

2024-05-29 09:04 UTC, MykytaDuniashev requested changes
The link for the API-docs documentation should be: https://api.elastic.io/docs/v2#/flows/post_flows__flow_id__copy

2024-05-30 08:12 UTC, MykytaDuniashev approved these changes

2024-05-30 08:12 UTC, merged